print('                       ╭━━╮                                         ')
print('                      ╭┻━━┻╮                                       ')
print('                      ┃╭╮╭╮┃                                     ')
print('                     ╭┫▕▎▕▎┣╮                                       ')
print('                     ╰┓┳╰╯┳┏╯                                        ')
print('                     ╭┛╰━━╯┗╮                                      ')
print('                     ┃┃    ┃┃                                       ')
print('                     ┃┃    ┃┃              ╭ ━ ╮                            ')
print('                     ╰┫ ╭╮ ┣╯           ┏━━┻━━━┻━━━┓                               ')
print('                      ┃ ┃┃ ┃            | OldSpice |                                  ')
print('                     ╭┛ ┃┃ ┗╮           ╰━━━━━━━━━━╯                                         ')
print('                                                                           ')
print('                                                                                                               (╯ ° □ °) ╯ (┻━┻)                      ')
